version: 1.0.0.{build}
image: Visual Studio 2017
configuration:
- Debug
- Release
platform: Any CPU
dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  assembly_version: 1.0.0.0
  file_version: '{version}'
  informational_version: '{version}-$(APPVEYOR_REPO_COMMIT)'
before_build:
- pwsh: nuget restore
build:
  publish_core_console: true
  parallel: true
  verbosity: minimal